export const CHANGE_LOCALE = "CHANGE_LOCALE";
export const LOGIN_USER_SUCCESS = "LOGIN_USER_SUCCESS";
export const LOGIN_USER_ERROR = "LOGIN_USER_ERROR";
export const LOGIN_USER_SUBMITING = "LOGIN_USER_SUBMITING";
export const SERVER_ERROR = "SERVER_ERROR";
export const SALEPOINT_CHANGE = "SALEPOINT_CHANGE";
export const SALEPOINT_SELECTED = "SALEPOINT_SELECTED";
export const SALEPOINT_CHANGE_ERROR = "SALEPOINT_CHANGE_ERROR";
