export const CHANGE_LOCALE = "CHANGE_LOCALE";
export const LOGIN_USER_SUCCESS = "LOGIN_USER_SUCCESS";
export const LOGIN_USER_ERROR = "LOGIN_USER_ERROR";
export const LOGIN_USER_SUBMITING = "LOGIN_USER_SUBMITING";
export const SERVER_ERROR = "SERVER_ERROR";
export const SALEPOINT_CHANGE = "SALEPOINT_CHANGE";
export const SALEPOINT_SELECTED = "SALEPOINT_SELECTED";
export const SALEPOINT_CHANGE_ERROR = "SALEPOINT_CHANGE_ERROR";
export const LOGOUT_USER_SUCCESS = "LOGOUT_USER_SUCCESS";
export const LOGOUT_USER_ERROR = "LOGOUT_USER_ERROR";
export const LOADING_PRODUCTS_SUCCESS = "LOADING_PRODUCTS_SUCCESS";
export const LOADING_PRODUCTS_ERROR = "LOADING_PRODUCTS_ERROR";
export const LOADING_PRODUCTS = "LOADING_PRODUCTS";

export const LOADING_CATEGORIES_ERROR = "LOADING_CATEGORIES_ERROR";
export const LOADING_CATEGORIES = "LOADING_CATEGORIES";
export const LOADING_CATEGORIES_SUCCESS = "LOADING_CATEGORIES_SUCCESS";

export const LOADING_MEMBERS_ERROR = "LOADING_MEMBERS_ERROR";
export const LOADING_MEMBERS = "LOADING_MEMBERS";
export const LOADING_MEMBERS_SUCCESS = "LOADING_MEMBERS_SUCCESS";

export const LOADING_SALEPOINTS_ERROR = "LOADING_SALEPOINTS_ERROR";
export const LOADING_SALEPOINTS = "LOADING_SALEPOINTS";
export const LOADING_SALEPOINTS_SUCCESS = "LOADING_SALEPOINTS_SUCCESS";
